name: flutter_ume_kit_designer_check
description: UI check tool for designer
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_ume: '>=0.3.0 <0.4.0'
  image_picker: ^0.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
